apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mistral-chatbot-pipeline
  annotations:
    scenarios.ai.sap.com/name: "mistral-chatbot"
    scenarios.ai.sap.com/description: "Conversational Mistral RAG chatbot for SAP OData running on FastAPI"
    executables.ai.sap.com/name: "mistral-chatbot-exec"
    executables.ai.sap.com/description: "Starts the chatbot API (uvicorn) in SAP AI Core"
  labels:
    scenarios.ai.sap.com/id: "mistral-chatbot"
    ai.sap.com/version: "1.0"

spec:
  # MUST match your Docker Registry Secret name in AI Core (case-sensitive)
  imagePullSecrets:
    - name: mistral-chatbot  # <-- change if your secret is named differently

  entrypoint: mistral-pipeline

  templates:
  - name: mistral-pipeline
    steps:
      - - name: chatbot-step
          template: mistral-chatbot

  - name: mistral-chatbot
    container:
      image: docker.io/sumitds1603/sap-agentic-rag-bot:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          set -e
          echo "Launching Mistral Conversational Agent..."
          mkdir -p /app/data /app/logs
          chmod -R 777 /app/data /app/logs || true
          uvicorn app:app --host 0.0.0.0 --port 8080

      env:
        - name: DEBUG
          value: "true"
        - name: ALLOW_INSECURE_HTTPS
          value: "true"
        - name: EMBED_MODEL_NAME
          value: "all-MiniLM-L6-v2"
        - name: DB_FILE
          value: "/app/data/sap_data.db"
        - name: FAISS_FILE
          value: "/app/data/sap_faiss.index"
        - name: LOG_FILE
          value: "/app/logs/agentic_ai_app.log"

        # SAP AI Core creds (Generic Secret must exist with these keys)
        - name: AICORE_DEPLOYMENT_ID
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_DEPLOYMENT_ID
        - name: AICORE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_CLIENT_ID
        - name: AICORE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_CLIENT_SECRET
        - name: AICORE_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_AUTH_URL
        - name: AICORE_BASE_URL
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_BASE_URL
        - name: AICORE_RESOURCE_GROUP
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_RESOURCE_GROUP

      # Start small to satisfy ResourceGroup quotas; increase after success
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "1"
          memory: "2Gi"

      ports:
        - name: http
          containerPort: 8080
