apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mistral-chatbot-pipeline
  annotations:
    scenarios.ai.sap.com/name: "mistral-chatbot"
    scenarios.ai.sap.com/description: "Conversational Mistral RAG chatbot for SAP OData running on FastAPI"
    executables.ai.sap.com/name: "mistral-chatbot-exec"
    executables.ai.sap.com/description: "Starts the chatbot API (uvicorn) in SAP AI Core"
  labels:
    scenarios.ai.sap.com/id: "mistral-chatbot"
    ai.sap.com/version: "1.0"

spec:
  imagePullSecrets:
    - name: mistralchatbotrepo   # this must match the Docker Registry Secret you created in Launchpad

  entrypoint: mistral-pipeline

  templates:
  - name: mistral-pipeline
    steps:
      - - name: chatbot-step
          template: mistral-chatbot

  - name: mistral-chatbot
    container:
      image: docker.io/sumitds1603/sap-agentic-rag-bot:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo " Launching Mistral Conversational Agent...";
          uvicorn app:app --host 0.0.0.0 --port 8080

      env:
        - name: DEBUG
          value: "false"
        - name: ALLOW_INSECURE_HTTPS
          value: "true"
        - name: EMBED_MODEL_NAME
          value: "all-MiniLM-L6-v2"
        - name: DB_FILE
          value: "/app/data/sap_data.db"
        - name: FAISS_FILE
          value: "/app/data/sap_faiss.index"
        - name: LOG_FILE
          value: "/app/logs/agentic_ai_app.log"

        # These next variables assume you created a generic secret
        # called mistral-chatbot-secrets in SAP AI Core with keys
        # AICORE_CLIENT_ID, etc.

        - name: AICORE_DEPLOYMENT_ID
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_DEPLOYMENT_ID
        - name: AICORE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_CLIENT_ID
        - name: AICORE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_CLIENT_SECRET
        - name: AICORE_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_AUTH_URL
        - name: AICORE_BASE_URL
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_BASE_URL
        - name: AICORE_RESOURCE_GROUP
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_RESOURCE_GROUP

      ports:
        - name: http
          containerPort: 8080

      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: "8Gi"
