apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mistral-chatbot-prod
  annotations:
    scenarios.ai.sap.com/description: "Production-grade Conversational RAG Bot powered by Mistral AI via SAP AI Core"
    scenarios.ai.sap.com/name: "Mistral Chatbot (Production)"
    executables.ai.sap.com/description: "Deploys and runs the Mistral-based conversational RAG FastAPI chatbot integrated with SAP OData"
    executables.ai.sap.com/name: "Mistral Chatbot"
  labels:
    scenarios.ai.sap.com/id: "sap-agentic-mistral-chatbot"
    ai.sap.com/version: "1.0"

spec:
  imagePullSecrets:
    - name: mistralchatbotrepo  # Your Docker registry secret configured in AI Core

  entrypoint: chatbot-pipeline

  templates:
  - name: chatbot-pipeline
    steps:
      - - name: run-chatbot
          template: chatbot-container

  - name: chatbot-container
    container:
      image: docker.io/sumitds1603/mistral-chatbot:latest  # Your Docker image
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Starting Mistral Conversational RAG Chatbot";
          uvicorn app:app --host 0.0.0.0 --port 8080

      env:
        - name: DEBUG
          value: "false"
        - name: ALLOW_INSECURE_HTTPS
          value: "true"
        - name: EMBED_MODEL_NAME
          value: "all-MiniLM-L6-v2"
        - name: DB_FILE
          value: "/app/data/sap_data.db"
        - name: FAISS_FILE
          value: "/app/data/sap_faiss.index"
        - name: LOG_FILE
          value: "/app/logs/agentic_ai_app.log"

        # --- Injecting SAP AI Core Credentials via Secrets ---
        - name: AICORE_DEPLOYMENT_ID
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_DEPLOYMENT_ID
        - name: AICORE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_CLIENT_ID
        - name: AICORE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_CLIENT_SECRET
        - name: AICORE_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_AUTH_URL
        - name: AICORE_BASE_URL
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_BASE_URL
        - name: AICORE_RESOURCE_GROUP
          valueFrom:
            secretKeyRef:
              name: mistral-chatbot-secrets
              key: AICORE_RESOURCE_GROUP

      ports:
        - name: http
          containerPort: 8080

      resources:
        limits:
          cpu: "4"
          memory: "8Gi"
        requests:
          cpu: "2"
          memory: "4Gi"

      volumeMounts:
        - name: data
          mountPath: /app/data
        - name: logs
          mountPath: /app/logs

    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mistral-chatbot-data
      - name: logs
        persistentVolumeClaim:
          claimName: mistral-chatbot-logs
